### ISSUE TITLE
PWM Motors not at the same time running

### ISSUE THREAD

**Issue by neblina-software** [openpilot/OpenPilot#3]
A2212-13T motors are running fine in pwm arduino, but not in open pilot at same time, any ideas?.

Note: Motor outputs are calibrated at the same level.

regards.

**Comment by parched** [comment]
Hi neblina, this is just a mirror, issue management is done at progress.openpilot.org although I think this may be best discussed at forums.openpilot.org as it might not be a bug, so feel free to start a thread there.
